import type { NextPage } from "next";
import Head from "next/head";

const BlogPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Joel Henry | Full Stack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>






      
    </>
  );
};
